// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-mhE8gCJl5PI5VwS-mKZ7cDhPB7jJILU',
    appId: '1:66811033735:web:6d6a68f970039919792022',
    messagingSenderId: '66811033735',
    projectId: 'signinsignup-2ac75',
    authDomain: 'signinsignup-2ac75.firebaseapp.com',
    storageBucket: 'signinsignup-2ac75.firebasestorage.app',
    measurementId: 'G-VDTVV94V00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7qyLkm8Y84GrgofAtaGgHCW5e5rh-9jc',
    appId: '1:66811033735:android:c630963177092a3e792022',
    messagingSenderId: '66811033735',
    projectId: 'signinsignup-2ac75',
    storageBucket: 'signinsignup-2ac75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfbw1glRHhhF3JEeGFj7lTpcXOqIreHCY',
    appId: '1:66811033735:ios:24f327d3c4a9add6792022',
    messagingSenderId: '66811033735',
    projectId: 'signinsignup-2ac75',
    storageBucket: 'signinsignup-2ac75.firebasestorage.app',
    iosBundleId: 'com.example.signinsignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfbw1glRHhhF3JEeGFj7lTpcXOqIreHCY',
    appId: '1:66811033735:ios:24f327d3c4a9add6792022',
    messagingSenderId: '66811033735',
    projectId: 'signinsignup-2ac75',
    storageBucket: 'signinsignup-2ac75.firebasestorage.app',
    iosBundleId: 'com.example.signinsignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-mhE8gCJl5PI5VwS-mKZ7cDhPB7jJILU',
    appId: '1:66811033735:web:e26166585f1935b0792022',
    messagingSenderId: '66811033735',
    projectId: 'signinsignup-2ac75',
    authDomain: 'signinsignup-2ac75.firebaseapp.com',
    storageBucket: 'signinsignup-2ac75.firebasestorage.app',
    measurementId: 'G-PZX3LG8WKH',
  );
}
